<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(SolutionDir)\valheim.targets" />
  <PropertyGroup>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <LangVersion>10</LangVersion>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="Jotunn">
      <HintPath>$(SolutionDir)\Plugins\Jotunn\Jotunn.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="assets\gold_bundle" />
    <EmbeddedResource Include="assets\blackmetal_bundle" />
    <EmbeddedResource Include="assets\iron_bundle" />
    <EmbeddedResource Include="assets\silver_bundle" />
    <EmbeddedResource Include="assets\coal_bundle" />
    <EmbeddedResource Include="assets\translations_bundle" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="Package\icon.png" />
    <Content Include="Translations\German\More Ore Deposits.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>